### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by gwidme01** [knightlab-analyses/horseshoe-analyses#1] opened 2019-06-03 02:19 UTC
conda create -n horseshoes --file ci/conda_requirements.txt  generates an error: 

Solving environment: failed
srun: error: omega001: task 0: Segmentation fault (core dumped)
Segmentation fault (core dumped)

I'm running Research Cluster running RedHat Enterprise Linux 6 and SLURM
Installed anaconda3 for Linux 64bit.

**Comment by gwidme01** [comment] 2019-06-03 02:34
running $ gdb binary-file core.34978
generated this report:
$ gdb binary-file core.34978
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
binary-file: No such file or directory.
[New Thread 34986]
[New Thread 34991]
[New Thread 34987]
[New Thread 34988]
[New Thread 34993]
[New Thread 34989]
[New Thread 34978]
[New Thread 34990]
[New Thread 34997]
[New Thread 34992]
[New Thread 34996]
[New Thread 34994]
Core was generated by `/cluster/tufts/gwidme01/anaconda3/bin/python /cluster/tufts/gwidme01/anaconda3/'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f236f03a7f6 in ?? ()

**Comment by mortonjt** [comment] 2019-06-03 09:38
hmm - that sounds like a conda error.  I've just redid the install on my mac, and didn't come across this problem.  

One possibility is that you are using anaconda -- rather than miniconda.  I'd suggest trying out [miniconda](https://docs.conda.io/en/latest/miniconda.html) -- anaconda is known to install a ton of bloat.

If that doesn't work -- it is possible that conda doesn't play nicely with your cluster (it does happen, particularly due to C interfaces).  In which case, you may have to jerry-rig your install with [virtualenv](https://docs.python.org/3/library/venv.html)

**Comment by mortonjt** [comment] 2019-06-09 18:43
@gwidme01, not sure if you were able to resolve this problem, but it sounds more like a conda issue.  Closing this issue for now.  Feel free to reopen if the issue is still a problem.

**Closed as completed by mortonjt** 2019-06-09 18:43 UTC

**Comment by gwidme01** [comment] 2019-06-14 17:52
Hi @mortonjt, what is the exact syntax for running embad.py? Thanks.
